// <auto-generated />
namespace Adani.Solution.Data.DatabaseContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class stpforeignkeyremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stpforeignkeyremove));
        
        string IMigrationMetadata.Id
        {
            get { return "202301171329111_stp-foreignkeyremove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
