// <auto-generated />
namespace Adani.Solution.Data.DatabaseContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class Gamification_Dashboard_Details_Table_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gamification_Dashboard_Details_Table_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202409040642344_Gamification_Dashboard_Details_Table_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
