set servername=ealdealdb.cpgq1slopli8.ap-south-1.rds.amazonaws.com
set dbName=EmamiPilotTesting
set userName=ealdealdbuser
set password=EalDeAlDb123

SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "ExpriyDateNotification.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Fn_Emami_GetPROO.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Fn_Tbl_Emami_GetOilTypePROO.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Notification.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_ Pricing and Location.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_All.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Broker.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Customer.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DepotCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Sp_Emami_ReportBusinessMargin.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Sp_Emami_ReportPlantwiseSauda.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Sp_Emami_ReportStateAndOilMargin.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "sp_MissingEntries.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_PricingExcelExport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Sku.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_UserCustomerSalesTarget.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_UserCustomerSaudaTarget.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_UserOilTypeTarget.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_UserSalesSaudaTarget.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Trigger_LiftingRequests_update.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Trigger_SaudaLimits_update.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Trigger_SaudaConversion_update.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Trigger_SaudaOrders_update.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "Trigger_SpecialRates_update.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "SP_Emami_DetentionCostReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "BiddingWindowDashboard.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "BiddingWindowDashboardDetails.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "BiddingWindowDashBoardVolumeCapacitiesChart.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "BiddingWindowDashboardReport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "GetFinalPriceDataExport.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "GetReverseAuctionFinalPriceDatas.sql"
SQLCMD /S %servername% /U %userName% /P %password% /d %dbName% -i "GetVolumeCapacityDetails.sql"

