using System.ComponentModel;

namespace Adani.Solution.DTO.Enums
{
    public enum Configuration
    {
        [Description("Notification Email")] NotificationEmail = 3,
        [Description("BidStatusTime")] BidStatusTime = 6,
        [Description("Counter Bid Buffer Time")] CounterBidBufferTime = 5,
        [Description("Is SMS")] IsSMS = 10,
        [Description("Is EMAIL")] IsEMAIL = 11,
        [Description("Is Push Notification")] IsPushNotification = 12,
        [Description("Login Base Hour")] LoginBaseHour = 13,
        [Description("Counter Bid Allow Count")] CounterBidCount = 14,
        [Description("Password Expiry Days")] PasswordExpiryDays = 15,
        [Description("Password Expiry Enabled")] PasswordExpiryEnabled = 16,
        [Description("Volume Capacity Notification Range")] VolumeCapacityNotificationRange = 17,
        [Description("Volume Capacity Notification Email")] VolumeCapacityNotificationEmail = 18,
        [Description("Expire Price Notification Days")] ExpirePriceNotificationDays = 19,
        [Description("Expire Price Notification Emails")] ExpirePriceNotificationEmails = 20,
        [Description("Bidding Window Time Interval")] BiddingWindowTimeInterval = 21,       
        [Description("Minimum Vehicle Capacity in Percent")] MinimumVehicleCapacityinPercent = 22,
        [Description("Support Features")] SupportFeatures = 23,
        [Description("Support Email")] SupportEmail = 24,
        [Description("Maximum Qty For Counter Bid Calculation")] MaximumQtyForCounterBidCalculation = 25,
        [Description("Maximum Bid For Counter Bid Calculation")] MaximumBidForCounterBidCalculation = 26,
        [Description("Sauda conversion Minimum Value")] SaudaconversionMinValue = 27,
        [Description("Sauda conversion Maximum Value")] SaudaconversionMaxValue = 28,
        [Description("Quantity Limit for Booking Sauda Enabled")] QuantityLimitforBookingSaudaEnabled = 29,
        [Description("Call Record Mapping Re-attach Buffer Time (Mins)")] CallRecordMappingReattachBufferTime = 30,
        [Description("Days For Audio Files Shown Against SaudaMapping")] DaysForAudioFilesShownAgainstSaudaMapping = 31,
        [Description("Audio Files Backup Days")] AudioFilesBackupDays = 32,
        [Description("Inbound Interface not Synced To SAP Minutes")] InboundInterfacenotSyncedToSAPMinutes = 33,
        [Description("Report Sync Date Validation In Hours")] ReportSyncDateValidationInHours = 34,
        [Description("Minimum Volume Capacity in Percent")] MinimumVolumeCapacityinPercent = 35,
        [Description("Discount Amount for Special Rate Approval")] DiscountAmountforSpecialRateApproval = 36,
        [Description("Maximum Vehicle Capacity in Percent")] MaximumVehicleCapacityinPercent = 37,
        [Description("Maximum Volume Capacity in Percent")] MaximumVolumeCapacityinPercent = 38,
        [Description("Sauda Extension Days")] SaudaExtensionDays = 39,
        [Description("Apply Speciality Fat Discount")] IsApplySpecialityFatDiscount = 40,
        [Description("Emails Based On Division For Sauda Report")] EmailsBasedOnDivisionForSaudaReport = 41,
        [Description("From Range 1")] FromRange1 = 42,
        [Description("To Range 1")] ToRange1 = 43,
        [Description("From Range 2")] FromRange2 = 44,
        [Description("To Range 2")] ToRange2 = 45,
        [Description("From Range 3")] FromRange3 = 46,
        [Description("To Range 3")] ToRange3 = 47,
        [Description("From Range 4")] FromRange4 = 48,
        [Description("To Range 4")] ToRange4= 49,
        [Description("From Range 5")] FromRange5 = 50,
        [Description("GPS Tracking Day To Delete record")] GPSTrackingDayToDeleteRecord = 51,
        [Description("Open Contract Time in Hrs")] OpenContractTimeInHrs = 52,
        [Description("Sauda Expire Notification")] SaudaExpireNotification = 53,
        [Description("Due Days Count")] DueDaysCount = 54,
        [Description("Sales Report Delete Days Count")] SalesReportDeleteDaysCount = 55,
        [Description("Customer Ledger Delete Days Count")] CustomerLedgerDeleteDaysCount = 56,
        [Description("Sauda Creation National Trader Approval")] SaudaCreationNationalTraderApproval = 57,
        [Description("Sauda Creation Zonal Trader Approval")] SaudaCreationZonalTraderApproval = 58,
        [Description("Account Statement Days")] AccountStatementDays = 66,
        [Description("Account Statement Hit Count")] AccountStatementHitCount = 37
    }
}
